name: ridex
description: "A cross-platform mobile application that revolutionizes ride-sharing through blockchain technology. Ride Pool connects drivers and passengers for efficient carpooling while leveraging Cardano's blockchain for secure, transparent transactions."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# this will be the version of the application in the format a.b.c+* where
# a is the major version, b is the minor version, c is the patch version,
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Here dependencies are listed.
dependencies:
  flutter:
    sdk: flutter

  cached_network_image:
  cupertino_icons: ^1.0.8
  dio:
  dots_indicator:
  flutter_animate:
  flutter_dotenv:
  flutter_local_notifications:
  flutter_screenutil:
  flutter_svg:
  get:
  gap:
  get_it:
  image_picker:
  intl:
  path:
  path_provider:
  provider:
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: BeauSans
      fonts:
        - asset: fonts/BT-BeauSans.ttf
        - asset: fonts/BT-BeauSans-Medium.ttf
        - asset: fonts/BT-BeauSans-Bold.ttf
          weight: 800
    - family: Zain
      fonts:
        - asset: fonts/Zain.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Regular.ttf
        - asset: fonts/Outfit-SemiBold.ttf
        - asset: fonts/Outfit.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 700
        - asset: fonts/Inter-Regular.otf

