name: ridex
description: "A cross-platform mobile application that revolutionizes ride-sharing through blockchain technology. Ride Pool connects drivers and passengers for efficient carpooling while leveraging Cardano's blockchain for secure, transparent transactions."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# this will be the version of the application in the format a.b.c+* where
# a is the major version, b is the minor version, c is the patch version,
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Here dependencies are listed.
dependencies:
  flutter:
    sdk: flutter

  cached_network_image:
  country_picker:
  cupertino_icons: ^1.0.8
  dio:
  dotenv:
  dots_indicator:
  flutter_animate:
  flutter_dotenv:
  flutter_local_notifications:
  flutter_multi_formatter:
  flutter_screenutil:
  flutter_svg:
  get:
  gap:
  get_it:
  geolocator:
  google_maps_flutter:
  image_picker:
  intl:
  maps_launcher:
  path:
  path_provider:
  pin_code_fields:
  provider:
  shared_preferences:
  connectivity_plus: ^6.1.4
  url_launcher:
  dotted_line_flutter: ^2.1.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  image: ^4.5.4
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  dotted_border: ^3.1.0
  http: ^1.4.0
  permission_handler: ^12.0.1
  workmanager: ^0.9.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: BeauSans
      fonts:
        - asset: fonts/BT-BeauSans.ttf
        - asset: fonts/BT-BeauSans-Medium.ttf
        - asset: fonts/BT-BeauSans-Bold.ttf
          weight: 800
    - family: Zain
      fonts:
        - asset: fonts/Zain.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Regular.ttf
        - asset: fonts/Outfit-SemiBold.ttf
        - asset: fonts/Outfit-Bold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 700
        - asset: fonts/Inter-Regular.otf

